export const PORT_80_CONFLICT = "PORT_80_CONFLICT";
export const PORT_443_CONFLICT = "PORT_443_CONFLICT";
export const SERVICE_NOT_FOUND = "SERVICE_NOT_FOUND";
export const DUPLICATE_HOST = "DUPLICATE_HOST";
export const INVALID_STACK_NAME = "INVALID_STACK_NAME";
export const PORT_EXPOSED = "PORT_EXPOSED";
export const NO_IMAGE_OR_BUILD = "NO_IMAGE_OR_BUILD";
